namespace ConfigApp
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using static ConfigApp.Effects;

    public static class ZChaosEffects
    {
        public static readonly Dictionary<string, EffectInfo> EffectsMap = new()
        {
            { "zchaos_portrait_mode", new("(ZChaos) Portrait Mode", EffectCategory.ZChaos, true) },
            { "zchaos_dvd_screensaver", new("(ZChaos) DVD Screensaver", EffectCategory.ZChaos, true) },
            { "zchaos_blind", new("(ZChaos) Blind", EffectCategory.ZChaos, true) },
            { "zchaos_nothing", new("(ZChaos) Nothing", EffectCategory.ZChaos, true) },
            { "zchaos_fake_lag", new("(ZChaos) Fake Lag", EffectCategory.ZChaos, true) },
            { "zchaos_anti-portrait_mode", new("(ZChaos) Anti-Portrait Mode", EffectCategory.ZChaos, true) },
            { "zchaos_sleepy_mode", new("(ZChaos) Sleepy Mode", EffectCategory.ZChaos, true) },
            { "zchaos_rainbowpls", new("(ZChaos) RainbowPls", EffectCategory.ZChaos, true) },
            { "zchaos_fake_crash", new("(ZChaos) Fake Crash", EffectCategory.ZChaos) },
            { "zchaos_4k_rtx_realistic_enb_simulator", new("(ZChaos) 4K RTX Realistic ENB Simulator", EffectCategory.ZChaos, true) },
            { "zchaos_fading_out", new("(ZChaos) Fading Out", EffectCategory.ZChaos, true) },
            { "zchaos_roll_chaos_credits", new("(ZChaos) Roll Chaos Credits", EffectCategory.ZChaos, true) },
            { "zchaos_roll_fast_chaos_credits", new("(ZChaos) Roll Fast Chaos Credits", EffectCategory.ZChaos, true) },
            { "zchaos_quantv_mode", new("(ZChaos) QuantV Mode", EffectCategory.ZChaos, true) },
            { "zchaos_combo_time", new("(ZChaos) Combo Time", EffectCategory.ZChaos, true) },
            { "zchaos_omega_combo_time", new("(ZChaos) OMEGA COMBO TIME", EffectCategory.ZChaos, true) },
            { "zchaos_double_subs", new("(ZChaos) Double Subs", EffectCategory.ZChaos) },
            { "zchaos_proportional_voting", new("(ZChaos) Proportional Voting", EffectCategory.ZChaos) },
            { "zchaos_no_voting", new("(ZChaos) No Voting", EffectCategory.ZChaos) },
            { "zchaos_least_voted_effect_wins", new("(ZChaos) Least Voted Effect Wins", EffectCategory.ZChaos) },
            { "zchaos_add_one_more_voting_option", new("(ZChaos) Add One More Voting Option", EffectCategory.ZChaos) },
            { "zchaos_30_second_timer", new("(ZChaos) 30 Second Timer", EffectCategory.ZChaos) },
            { "zchaos_cheat_code_voting", new("(ZChaos) Cheat Code Voting", EffectCategory.ZChaos, true) },
            { "zchaos_3_random_effects", new("(ZChaos) 3 Random Effects", EffectCategory.ZChaos) },
            { "zchaos_trigger_a_disabled_effect", new("(ZChaos) Trigger a Disabled Effect", EffectCategory.ZChaos) },
            { "zchaos_clear_active_effects", new("(ZChaos) Clear Active Effects", EffectCategory.ZChaos) },
            { "zchaos_refill_active_effect_timers", new("(ZChaos) Refill Active Effect Timers", EffectCategory.ZChaos) },
            { "zchaos_disable_chaos_ui", new("(ZChaos) Disable Chaos UI", EffectCategory.ZChaos) },
            { "zchaos_virtual_boy", new("(ZChaos) Virtual Boy", EffectCategory.ZChaos, true) },
            { "zchaos_pink", new("(ZChaos) Pink", EffectCategory.ZChaos, true) },
            { "zchaos_night_vision", new("(ZChaos) Night Vision", EffectCategory.ZChaos, true) },
            { "zchaos_piss_filter", new("(ZChaos) Piss Filter", EffectCategory.ZChaos, true) },
            { "zchaos_negative", new("(ZChaos) Negative", EffectCategory.ZChaos, true) },
            { "zchaos_creepypasta_mode", new("(ZChaos) Creepypasta Mode", EffectCategory.ZChaos, true) },
            { "zchaos_kappagen", new("(ZChaos) KappaGen", EffectCategory.ZChaos, true) },
            { "zchaos_colors", new("(ZChaos) Colors", EffectCategory.ZChaos, true) },
            { "zchaos_lsd_trip", new("(ZChaos) LSD Trip", EffectCategory.ZChaos, true) },
            { "zchaos_murder_gpu_in_cold_blood", new("(ZChaos) Murder GPU in cold blood", EffectCategory.ZChaos, true) },
            { "zchaos_is_this_a_jojo_reference", new("(ZChaos) Is this a JoJo reference?", EffectCategory.ZChaos, true) },
            { "zchaos_low_res_gaming", new("(ZChaos) Low Res Gaming", EffectCategory.ZChaos, true) },
            { "zchaos_very_low_res_gaming", new("(ZChaos) Very Low Res Gaming", EffectCategory.ZChaos, true) },
            { "zchaos_mom_said_its_my_turn_on_the_pixel", new("(ZChaos) Mom said it's my turn on the pixel", EffectCategory.ZChaos, true) },
            { "zchaos_real_vr_experience", new("(ZChaos) Real VR Experience", EffectCategory.ZChaos, true) },
            { "zchaos_literal_tunnel_vision", new("(ZChaos) Literal Tunnel Vision", EffectCategory.ZChaos, true) },
            { "zchaos_see_more", new("(ZChaos) See More", EffectCategory.ZChaos, true) },
            { "zchaos_screercs", new("(ZChaos) ScreercS", EffectCategory.ZChaos, true) },
            { "zchaos_fuuf", new("(ZChaos) FuuF", EffectCategory.ZChaos, true) },
            { "zchaos_256_color_mode", new("(ZChaos) 256 Color Mode", EffectCategory.ZChaos, true) },
            { "zchaos_24_color_mode", new("(ZChaos) 24 Color Mode", EffectCategory.ZChaos, true) },
            { "zchaos_8_color_mode", new("(ZChaos) 8 Color Mode", EffectCategory.ZChaos, true) },
            { "zchaos_minigame_pong", new("(ZChaos) Minigame: Pong", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_pong", new("(ZChaos) Minigame: Hardcore Pong", EffectCategory.ZChaos) },
            { "zchaos_minigame_tetris", new("(ZChaos) Minigame: Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_tetris", new("(ZChaos) Minigame: Hardcore Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_very_hardcore_tetris", new("(ZChaos) Minigame: Very Hardcore Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_nes_tetris", new("(ZChaos) Minigame: NES Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_nes_tetris", new("(ZChaos) Minigame: Hardcore NES Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_very_hardcore_nes_tetris", new("(ZChaos) Minigame: Very Hardcore NES Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_chat_sabotages_tetris", new("(ZChaos) Minigame: Chat Sabotages Tetris", EffectCategory.ZChaos) },
            { "zchaos_minigame_guitar_hero", new("(ZChaos) Minigame: Guitar Hero", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_guitar_hero", new("(ZChaos) Minigame: Hardcore Guitar Hero", EffectCategory.ZChaos) },
            { "zchaos_minigame_snake", new("(ZChaos) Minigame: Snake", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_snake", new("(ZChaos) Minigame: Hardcore Snake", EffectCategory.ZChaos) },
            { "zchaos_minigame_plants_vs_zombies", new("(ZChaos) Minigame: Plants vs Zombies", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_plants_vs_zombies", new("(ZChaos) Minigame: Hardcore Plants vs Zombies", EffectCategory.ZChaos) },
            { "zchaos_minigame_chat_sabotages_plants_vs_zombies", new("(ZChaos) Minigame: Chat Sabotages Plants vs Zombies", EffectCategory.ZChaos) },
            { "zchaos_minigame_password_game", new("(ZChaos) Minigame: Password Game", EffectCategory.ZChaos) },
            { "zchaos_minigame_hardcore_password_game", new("(ZChaos) Minigame: Hardcore Password Game", EffectCategory.ZChaos) },
            { "zchaos_minigame_project_diva", new("(ZChaos) Minigame: Project DIVA", EffectCategory.ZChaos) },
            { "zchaos_accurate_enb_simulator", new("(ZChaos) Accurate ENB Simulator", EffectCategory.ZChaos, true) },
            { "zchaos_earthquake", new("(ZChaos) Earthquake", EffectCategory.ZChaos, true) },
            { "zchaos_invert_current_velocity", new("(ZChaos) Invert Current Velocity", EffectCategory.ZChaos) },
            { "zchaos_no_hud", new("(ZChaos) No HUD", EffectCategory.ZChaos, true) },
            { "zchaos_one_bullet_mags", new("(ZChaos) One Bullet Mags", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_jet", new("(ZChaos) Spawn Jet", EffectCategory.ZChaos) },
            { "zchaos_spinning_traffic", new("(ZChaos) Spinning Traffic", EffectCategory.ZChaos, true) },
            { "zchaos_aimbot_peds", new("(ZChaos) Aimbot Peds", EffectCategory.ZChaos, true) },
            { "zchaos_everyone_leaves_all_vehicles", new("(ZChaos) Everyone Leaves All Vehicles", EffectCategory.ZChaos) },
            { "zchaos_everyone_ignores_player", new("(ZChaos) Everyone Ignores Player", EffectCategory.ZChaos, true) },
            { "zchaos_explosive_peds", new("(ZChaos) Explosive Peds", EffectCategory.ZChaos, true) },
            { "zchaos_give_everyone_rpgs", new("(ZChaos) Give Everyone RPGs", EffectCategory.ZChaos) },
            { "zchaos_godmode_for_all_peds", new("(ZChaos) Godmode for All Peds", EffectCategory.ZChaos, true) },
            { "zchaos_ignite_all_peds", new("(ZChaos) Ignite All Peds", EffectCategory.ZChaos) },
            { "zchaos_launch_all_peds", new("(ZChaos) Launch All Peds", EffectCategory.ZChaos) },
            { "zchaos_explode_all_peds", new("(ZChaos) Explode All Peds", EffectCategory.ZChaos) },
            { "zchaos_disarm_all_peds", new("(ZChaos) Disarm All Peds", EffectCategory.ZChaos) },
            { "zchaos_one_hit_ko", new("(ZChaos) One Hit KO", EffectCategory.ZChaos, true) },
            { "zchaos_give_armor", new("(ZChaos) Give Armor", EffectCategory.ZChaos) },
            { "zchaos_bankrupt", new("(ZChaos) Bankrupt", EffectCategory.ZChaos) },
            { "zchaos_no_control", new("(ZChaos) No Control", EffectCategory.ZChaos, true) },
            { "zchaos_exit_current_vehicle", new("(ZChaos) Exit Current Vehicle", EffectCategory.ZChaos) },
            { "zchaos_give_all_weapons", new("(ZChaos) Give All Weapons", EffectCategory.ZChaos) },
            { "zchaos_give_rpg", new("(ZChaos) Give RPG", EffectCategory.ZChaos) },
            { "zchaos_give_grenade", new("(ZChaos) Give Grenade", EffectCategory.ZChaos) },
            { "zchaos_give_molotov", new("(ZChaos) Give Molotov", EffectCategory.ZChaos) },
            { "zchaos_give_health", new("(ZChaos) Give Health", EffectCategory.ZChaos) },
            { "zchaos_give_a_lot_of_health", new("(ZChaos) Give A LOT of health", EffectCategory.ZChaos) },
            { "zchaos_ignite_player", new("(ZChaos) Ignite Player", EffectCategory.ZChaos) },
            { "zchaos_launch_player", new("(ZChaos) Launch Player", EffectCategory.ZChaos) },
            { "zchaos_ragdoll_player", new("(ZChaos) Ragdoll Player", EffectCategory.ZChaos) },
            { "zchaos_random_outfit", new("(ZChaos) Random Outfit", EffectCategory.ZChaos) },
            { "zchaos_remove_all_weapons", new("(ZChaos) Remove All Weapons", EffectCategory.ZChaos) },
            { "zchaos_teleport_into_closest_seat", new("(ZChaos) Teleport into Closest Seat", EffectCategory.ZChaos) },
            { "zchaos_kill_player", new("(ZChaos) Kill Player", EffectCategory.ZChaos) },
            { "zchaos_teleport_to_top_of_maze_bank_tower", new("(ZChaos) Teleport to Top of Maze Bank Tower", EffectCategory.ZChaos) },
            { "zchaos_teleport_to_waypoint", new("(ZChaos) Teleport to Waypoint", EffectCategory.ZChaos) },
            { "zchaos_5_star_wanted_level", new("(ZChaos) 5 Star Wanted Level", EffectCategory.ZChaos) },
            { "zchaos_clear_wanted_level", new("(ZChaos) Clear Wanted Level", EffectCategory.ZChaos) },
            { "zchaos_piracy", new("(ZChaos) Piracy", EffectCategory.ZChaos, true) },
            { "zchaos_forward_game_clock_by_a_day", new("(ZChaos) Forward Game Clock by a Day", EffectCategory.ZChaos) },
            { "zchaos_reverse_game_clock_by_a_day", new("(ZChaos) Reverse Game Clock by a Day", EffectCategory.ZChaos) },
            { "zchaos_slow-mo", new("(ZChaos) Slow-mo", EffectCategory.ZChaos, true) },
            { "zchaos_game_speedup", new("(ZChaos) Game Speedup", EffectCategory.ZChaos, true) },
            { "zchaos_timelapse", new("(ZChaos) Timelapse", EffectCategory.ZChaos, true) },
            { "zchaos_clean_car", new("(ZChaos) Clean Car", EffectCategory.ZChaos) },
            { "zchaos_make_car_dirty", new("(ZChaos) Make Car Dirty", EffectCategory.ZChaos) },
            { "zchaos_explode_car", new("(ZChaos) Explode Car", EffectCategory.ZChaos) },
            { "zchaos_pedal_to_the_metal", new("(ZChaos) Pedal to the Metal", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_tug", new("(ZChaos) Spawn Tug", EffectCategory.ZChaos) },
            { "zchaos_rainbow_traffic", new("(ZChaos) Rainbow Traffic", EffectCategory.ZChaos, true) },
            { "zchaos_explode_on_foot", new("(ZChaos) Explode On Foot", EffectCategory.ZChaos) },
            { "zchaos_spawn_random_car", new("(ZChaos) Spawn Random Car", EffectCategory.ZChaos) },
            { "zchaos_super_jump", new("(ZChaos) Super Jump", EffectCategory.ZChaos, true) },
            { "zchaos_wheelsonlyplease", new("(ZChaos) WHEELSONLYPLEASE", EffectCategory.ZChaos, true) },
            { "zchaos_no_water", new("(ZChaos) No Water", EffectCategory.ZChaos, true) },
            { "zchaos_explosive_bullets", new("(ZChaos) Explosive Bullets", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_all_peds_to_you", new("(ZChaos) Teleport All Peds To You", EffectCategory.ZChaos) },
            { "zchaos_kill_all_cops", new("(ZChaos) Kill All Cops", EffectCategory.ZChaos) },
            { "zchaos_vehicle_impostor_sus", new("(ZChaos) Vehicle Impostor sus", EffectCategory.ZChaos, true) },
            { "zchaos_slide_run", new("(ZChaos) Slide Run", EffectCategory.ZChaos, true) },
            { "zchaos_superlods", new("(ZChaos) SuperLODs", EffectCategory.ZChaos, true) },
            { "zchaos_no_crosshair", new("(ZChaos) No Crosshair", EffectCategory.ZChaos, true) },
            { "zchaos_no_sprinting", new("(ZChaos) No Sprinting", EffectCategory.ZChaos, true) },
            { "zchaos_zoomed_out_radar", new("(ZChaos) Zoomed Out Radar", EffectCategory.ZChaos, true) },
            { "zchaos_high_bulletspread", new("(ZChaos) High Bulletspread", EffectCategory.ZChaos, true) },
            { "zchaos_its_bright_in_here", new("(ZChaos) It's bright in here", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_to_north_blip", new("(ZChaos) Teleport to north blip", EffectCategory.ZChaos) },
            { "zchaos_relative_car_gravity", new("(ZChaos) Relative Car Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_float_above_cars", new("(ZChaos) Float Above Cars", EffectCategory.ZChaos, true) },
            { "zchaos_bright_car_headlights", new("(ZChaos) Bright Car Headlights", EffectCategory.ZChaos, true) },
            { "zchaos_non-solid_car", new("(ZChaos) Non-Solid Car", EffectCategory.ZChaos, true) },
            { "zchaos_freeze_car", new("(ZChaos) Freeze Car", EffectCategory.ZChaos, true) },
            { "zchaos_delete_car", new("(ZChaos) Delete Car", EffectCategory.ZChaos) },
            { "zchaos_fuck_up_car", new("(ZChaos) Fuck Up Car", EffectCategory.ZChaos, true) },
            { "zchaos_detach_all_car_parts", new("(ZChaos) Detach all Car Parts", EffectCategory.ZChaos, true) },
            { "zchaos_attach_to_nearest_car", new("(ZChaos) Attach to Nearest Car", EffectCategory.ZChaos, true) },
            { "zchaos_no_car_gravity", new("(ZChaos) No Car Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_give_everyone_m4s", new("(ZChaos) Give Everyone M4s", EffectCategory.ZChaos) },
            { "zchaos_give_everyone_snipers", new("(ZChaos) Give Everyone Snipers", EffectCategory.ZChaos) },
            { "zchaos_burst_car_tyres", new("(ZChaos) Burst Car Tyres", EffectCategory.ZChaos) },
            { "zchaos_fix_car", new("(ZChaos) Fix Car", EffectCategory.ZChaos) },
            { "zchaos_no_collision_on_foot", new("(ZChaos) No Collision on Foot", EffectCategory.ZChaos, true) },
            { "zchaos_jump_forward", new("(ZChaos) Jump Forward", EffectCategory.ZChaos) },
            { "zchaos_fire_bullets", new("(ZChaos) Fire Bullets", EffectCategory.ZChaos, true) },
            { "zchaos_thank_you_1351", new("(ZChaos) Thank you 1351", EffectCategory.ZChaos) },
            { "zchaos_fuck_you_1351", new("(ZChaos) Fuck you 1351", EffectCategory.ZChaos) },
            { "zchaos_delete_all_cars", new("(ZChaos) Delete All Cars", EffectCategory.ZChaos) },
            { "zchaos_all_peds_drop_32767", new("(ZChaos) All Peds Drop $32767", EffectCategory.ZChaos, true) },
            { "zchaos_all_peds_drop_0", new("(ZChaos) All Peds Drop $0", EffectCategory.ZChaos, true) },
            { "zchaos_sacrificial_circle", new("(ZChaos) Sacrificial Circle", EffectCategory.ZChaos) },
            { "zchaos_millionaire", new("(ZChaos) Millionaire", EffectCategory.ZChaos) },
            { "zchaos_void_warp", new("(ZChaos) Void Warp", EffectCategory.ZChaos) },
            { "zchaos_default_clothes", new("(ZChaos) Default Clothes", EffectCategory.ZChaos) },
            { "zchaos_switch_to_unarmed", new("(ZChaos) Switch to Unarmed", EffectCategory.ZChaos) },
            { "zchaos_switch_to_most_inconvenient_weapon", new("(ZChaos) Switch to Most Inconvenient Weapon", EffectCategory.ZChaos) },
            { "zchaos_blooooom", new("(ZChaos) BLOOOOOM", EffectCategory.ZChaos, true) },
            { "zchaos_no_signal", new("(ZChaos) No Signal", EffectCategory.ZChaos, true) },
            { "zchaos_low_draw_distance", new("(ZChaos) Low Draw Distance", EffectCategory.ZChaos, true) },
            { "zchaos_pink_world", new("(ZChaos) Pink World", EffectCategory.ZChaos, true) },
            { "zchaos_no_fog", new("(ZChaos) No Fog", EffectCategory.ZChaos, true) },
            { "zchaos_hyper_lsd_mode", new("(ZChaos) Hyper LSD Mode", EffectCategory.ZChaos, true) },
            { "zchaos_noire", new("(ZChaos) Noire", EffectCategory.ZChaos, true) },
            { "zchaos_hell", new("(ZChaos) Hell", EffectCategory.ZChaos, true) },
            { "zchaos_apocalypse_weather", new("(ZChaos) Apocalypse Weather", EffectCategory.ZChaos, true) },
            { "zchaos_poop", new("(ZChaos) Poop", EffectCategory.ZChaos, true) },
            { "zchaos_drive_wander", new("(ZChaos) Drive Wander", EffectCategory.ZChaos, true) },
            { "zchaos_walk_off", new("(ZChaos) Walk Off", EffectCategory.ZChaos, true) },
            { "zchaos_no_tasks_allowed", new("(ZChaos) No Tasks Allowed", EffectCategory.ZChaos, true) },
            { "zchaos_drunk_ragdoll", new("(ZChaos) Drunk Ragdoll", EffectCategory.ZChaos, true) },
            { "zchaos_steer_bias", new("(ZChaos) Steer Bias", EffectCategory.ZChaos, true) },
            //{ "zchaos_steer_bias", new("(ZChaos) Steer Bias", EffectCategory.ZChaos, true) },
            { "zchaos_trackmania_canyon_camera", new("(ZChaos) TrackMania Canyon Camera", EffectCategory.ZChaos, true) },
            { "zchaos_whered_the_world_go", new("(ZChaos) Where'd the world go?", EffectCategory.ZChaos, true) },
            { "zchaos_raining_cars", new("(ZChaos) Raining Cars", EffectCategory.ZChaos) },
            { "zchaos_ignite_car", new("(ZChaos) Ignite Car", EffectCategory.ZChaos) },
            { "zchaos_inaccurate_peds", new("(ZChaos) Inaccurate Peds", EffectCategory.ZChaos, true) },
            { "zchaos_420am", new("(ZChaos) 4:20AM", EffectCategory.ZChaos) },
            { "zchaos_420pm", new("(ZChaos) 4:20PM", EffectCategory.ZChaos) },
            { "zchaos_need_a_taxi", new("(ZChaos) Need a Taxi?", EffectCategory.ZChaos) },
            { "zchaos_note_7", new("(ZChaos) Note 7", EffectCategory.ZChaos, true) },
            { "zchaos_car_speedup", new("(ZChaos) Car Speedup", EffectCategory.ZChaos) },
            { "zchaos_new_game_tf", new("(ZChaos) New Game :tf:", EffectCategory.ZChaos) },
            { "zchaos_autosave_off", new("(ZChaos) Autosave Off", EffectCategory.ZChaos, true) },
            { "zchaos_take_damage", new("(ZChaos) Take Damage", EffectCategory.ZChaos) },
            { "zchaos_quake_pro", new("(ZChaos) Quake Pro", EffectCategory.ZChaos, true) },
            { "zchaos_low_fov", new("(ZChaos) Low FOV", EffectCategory.ZChaos, true) },
            { "zchaos_fake_explosion", new("(ZChaos) Fake Explosion", EffectCategory.ZChaos) },
            { "zchaos_airbreak", new("(ZChaos) Airbreak", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_maverick", new("(ZChaos) Spawn Maverick", EffectCategory.ZChaos) },
            { "zchaos_spawn_annihilator", new("(ZChaos) Spawn Annihilator", EffectCategory.ZChaos) },
            { "zchaos_godmode", new("(ZChaos) Godmode", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_to_top_of_maze_bank_tower_but_with_godmode", new("(ZChaos) Teleport to Top of Maze Bank Tower but with Godmode", EffectCategory.ZChaos, true) },
            { "zchaos_sticky_1_star_wanted_level", new("(ZChaos) Sticky 1 Star Wanted Level", EffectCategory.ZChaos, true) },
            { "zchaos_remove_armor", new("(ZChaos) Remove Armor", EffectCategory.ZChaos) },
            { "zchaos_ignite_all_taxis", new("(ZChaos) Ignite All Taxis", EffectCategory.ZChaos) },
            { "zchaos_ignite_all_cars", new("(ZChaos) Ignite All Cars", EffectCategory.ZChaos) },
            { "zchaos_ped_wallhack", new("(ZChaos) Ped Wallhack", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_to_airport", new("(ZChaos) Teleport to Airport", EffectCategory.ZChaos) },
            { "zchaos_public_transport", new("(ZChaos) Public Transport", EffectCategory.ZChaos) },
            { "zchaos_never_tired", new("(ZChaos) Never Tired", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_to_heaven", new("(ZChaos) Teleport to Heaven", EffectCategory.ZChaos) },
            { "zchaos_fully_tune_car", new("(ZChaos) Fully Tune Car", EffectCategory.ZChaos) },
            { "zchaos_lock_mouse__right_stick", new("(ZChaos) Lock Mouse & Right Stick", EffectCategory.ZChaos, true) },
            { "zchaos_no_water_collision", new("(ZChaos) No Water Collision", EffectCategory.ZChaos, true) },
            { "zchaos_no_ragdolls", new("(ZChaos) No Ragdolls", EffectCategory.ZChaos, true) },
            { "zchaos_give_everyone_random_weapons", new("(ZChaos) Give Everyone Random Weapons", EffectCategory.ZChaos) },
            { "zchaos_burst_all_cars_tyres", new("(ZChaos) Burst All Cars' Tyres", EffectCategory.ZChaos) },
            { "zchaos_ragdoll_on_damage", new("(ZChaos) Ragdoll on Damage", EffectCategory.ZChaos, true) },
            { "zchaos_portal_guns", new("(ZChaos) Portal Guns", EffectCategory.ZChaos, true) },
            { "zchaos_ragdoll_everyone", new("(ZChaos) Ragdoll Everyone", EffectCategory.ZChaos) },
            { "zchaos_ragdoll_all_peds", new("(ZChaos) Ragdoll All Peds", EffectCategory.ZChaos) },
            { "zchaos_beyblades", new("(ZChaos) Beyblades", EffectCategory.ZChaos, true) },
            { "zchaos_honk_boosting", new("(ZChaos) Honk Boosting", EffectCategory.ZChaos, true) },
            { "zchaos_gravity_field", new("(ZChaos) Gravity Field", EffectCategory.ZChaos, true) },
            { "zchaos_invisible_cars", new("(ZChaos) Invisible Cars", EffectCategory.ZChaos, true) },
            { "zchaos_forcefield", new("(ZChaos) Forcefield", EffectCategory.ZChaos, true) },
            { "zchaos_disable_leftright_movement", new("(ZChaos) Disable Left/Right Movement", EffectCategory.ZChaos, true) },
            { "zchaos_disable_forwardbackwards_movement", new("(ZChaos) Disable Forward/Backwards Movement", EffectCategory.ZChaos, true) },
            { "zchaos_force_acceleration", new("(ZChaos) Force Acceleration", EffectCategory.ZChaos, true) },
            { "zchaos_forced_walk", new("(ZChaos) Forced Walk", EffectCategory.ZChaos, true) },
            { "zchaos_forced_shoot", new("(ZChaos) Forced Shoot", EffectCategory.ZChaos, true) },
            { "zchaos_forced_aim", new("(ZChaos) Forced Aim", EffectCategory.ZChaos, true) },
            { "zchaos_forced_look_behind", new("(ZChaos) Forced Look Behind", EffectCategory.ZChaos, true) },
            { "zchaos_disable_shooting", new("(ZChaos) Disable Shooting", EffectCategory.ZChaos, true) },
            { "zchaos_disable_aiming", new("(ZChaos) Disable Aiming", EffectCategory.ZChaos, true) },
            { "zchaos_disable_brakes", new("(ZChaos) Disable Brakes", EffectCategory.ZChaos, true) },
            { "zchaos_give_random_car_a_bomb", new("(ZChaos) Give Random Car a Bomb", EffectCategory.ZChaos) },
            { "zchaos_pacifist", new("(ZChaos) Pacifist", EffectCategory.ZChaos, true) },
            { "zchaos_tryhard_mode", new("(ZChaos) Tryhard Mode", EffectCategory.ZChaos, true) },
            { "zchaos_its_easier_to_aim_they_said", new("(ZChaos) \"It's easier to aim\", they said", EffectCategory.ZChaos, true) }, 
            { "zchaos_invisible_player", new("(ZChaos) Invisible Player", EffectCategory.ZChaos, true) },
            { "zchaos_gta_2", new("(ZChaos) GTA 2", EffectCategory.ZChaos, true) },
            { "zchaos_is_it_easier_to_aim_yet", new("(ZChaos) Is it easier to aim yet?", EffectCategory.ZChaos, true) },
            { "zchaos_nightmare_fuel", new("(ZChaos) Nightmare fuel", EffectCategory.ZChaos, true) },
            { "zchaos_randomize_phone", new("(ZChaos) Randomize Phone", EffectCategory.ZChaos) },
            { "zchaos_good_luck", new("(ZChaos) Good luck", EffectCategory.ZChaos, true) },
            { "zchaos_drive_on_water", new("(ZChaos) Drive on Water", EffectCategory.ZChaos, true) },
            { "zchaos_drive_on_air", new("(ZChaos) Drive on Air", EffectCategory.ZChaos, true) },
            { "zchaos_oh_god_what_have_you_done", new("(ZChaos) Oh god what have you done", EffectCategory.ZChaos, true) },
            { "zchaos_lift_me_up", new("(ZChaos) Lift Me Up", EffectCategory.ZChaos, true) },
            { "zchaos_flip_screen", new("(ZChaos) Flip Screen", EffectCategory.ZChaos, true) },
            { "zchaos_juiced_2_ds", new("(ZChaos) Juiced 2 DS", EffectCategory.ZChaos, true) },
            { "zchaos_bouncy_cars", new("(ZChaos) Bouncy Cars", EffectCategory.ZChaos, true) },
            { "zchaos_slightly_bouncy_cars", new("(ZChaos) Slightly Bouncy Cars", EffectCategory.ZChaos, true) },
            { "zchaos_very_bouncy_cars", new("(ZChaos) Very Bouncy Cars", EffectCategory.ZChaos, true) },
            { "zchaos_riolu_mode", new("(ZChaos) Riolu Mode", EffectCategory.ZChaos, true) },
            { "zchaos_too_much_information", new("(ZChaos) Too Much Information", EffectCategory.ZChaos, true) },
            { "zchaos_australia_mode", new("(ZChaos) Australia Mode", EffectCategory.ZChaos, true) },
            { "zchaos_goodbye", new("(ZChaos) Goodbye", EffectCategory.ZChaos, true) },
            { "zchaos_stop", new("(ZChaos) Stop", EffectCategory.ZChaos) },
            { "zchaos_wrong_way", new("(ZChaos) Wrong Way", EffectCategory.ZChaos) },
            { "zchaos_helixsnake_mode", new("(ZChaos) HelixSnake Mode", EffectCategory.ZChaos, true) },
            { "zchaos_let_it_rip", new("(ZChaos) LET IT RIP", EffectCategory.ZChaos, true) },
            { "zchaos_pinball", new("(ZChaos) Pinball", EffectCategory.ZChaos, true) },
            { "zchaos_physics_have_left_the_chat", new("(ZChaos) Physics have left the chat", EffectCategory.ZChaos, true) },
            { "zchaos_permanently_disable_taxis", new("(ZChaos) Permanently disable taxis", EffectCategory.ZChaos) },
            { "zchaos_enable_taxis", new("(ZChaos) Enable Taxis", EffectCategory.ZChaos) },
            { "zchaos_need_for_speed", new("(ZChaos) Need for Speed", EffectCategory.ZChaos, true) },
            { "zchaos_grug_smash", new("(ZChaos) GRUG SMASH", EffectCategory.ZChaos) },
            { "zchaos_gravity_guns", new("(ZChaos) Gravity Guns", EffectCategory.ZChaos, true) },
            { "zchaos_switch_to_random_vehicle", new("(ZChaos) Switch to Random Vehicle", EffectCategory.ZChaos) },
            { "zchaos_skip_song", new("(ZChaos) Skip Song", EffectCategory.ZChaos) },
            { "zchaos_random_weather", new("(ZChaos) Random Weather", EffectCategory.ZChaos) },
            { "zchaos_i_said_something_nice_not_expensive", new("(ZChaos) I said something nice, not expensive", EffectCategory.ZChaos) },
            { "zchaos_tall_bois", new("(ZChaos) Tall Bois", EffectCategory.ZChaos, true) },
            { "zchaos_youve_been_struck_by", new("(ZChaos) You've been struck by", EffectCategory.ZChaos) },
            { "zchaos_packet_loss", new("(ZChaos) Packet Loss", EffectCategory.ZChaos, true) },
            { "zchaos_gta_-2", new("(ZChaos) GTA -2", EffectCategory.ZChaos, true) },
            { "zchaos_crossroads_mode", new("(ZChaos) Crossroads Mode", EffectCategory.ZChaos, true) },
            { "zchaos_handbrake_hopping", new("(ZChaos) Handbrake Hopping", EffectCategory.ZChaos, true) },
            { "zchaos_pause", new("(ZChaos) Pause", EffectCategory.ZChaos) },
            { "zchaos_standstill", new("(ZChaos) Standstill", EffectCategory.ZChaos, true) },
            { "zchaos_crazy_steering", new("(ZChaos) Crazy Steering", EffectCategory.ZChaos, true) },
            { "zchaos_prologue_phone", new("(ZChaos) Prologue Phone", EffectCategory.ZChaos, true) },
            { "zchaos_trackmania_stadium_camera", new("(ZChaos) TrackMania Stadium Camera", EffectCategory.ZChaos, true) },
            { "zchaos_trucked", new("(ZChaos) TRUCKED", EffectCategory.ZChaos) },
            { "zchaos_w_i_d_e___p_l_a_y_e_r", new("(ZChaos) W I D E   P L A Y E R", EffectCategory.ZChaos, true) },
            { "zchaos_give_re-volt_star", new("(ZChaos) Give Re-Volt Star", EffectCategory.ZChaos, true) },
            { "zchaos_give_re-volt_shockwave", new("(ZChaos) Give Re-Volt Shockwave", EffectCategory.ZChaos, true) },
            { "zchaos_give_re-volt_turbo", new("(ZChaos) Give Re-Volt Turbo", EffectCategory.ZChaos, true) },
            { "zchaos_give_re-volt_fake_pickup", new("(ZChaos) Give Re-Volt Fake Pickup", EffectCategory.ZChaos, true) },
            { "zchaos_launch_into_narnia", new("(ZChaos) Launch into Narnia", EffectCategory.ZChaos, true) },
            { "zchaos_x10_gravity", new("(ZChaos) X10 Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_no_pausing", new("(ZChaos) No Pausing", EffectCategory.ZChaos, true) },
            { "zchaos_literally_gta_iv", new("(ZChaos) Literally GTA IV", EffectCategory.ZChaos, true) },
            { "zchaos_definitive_edition", new("(ZChaos) Definitive Edition", EffectCategory.ZChaos, true) },
            { "zchaos_infinite_weapon_range", new("(ZChaos) Infinite Weapon Range", EffectCategory.ZChaos, true) },
            { "zchaos_no_range", new("(ZChaos) No Range?", EffectCategory.ZChaos, true) },
            { "zchaos_no_vehicle_air_control", new("(ZChaos) No Vehicle Air Control", EffectCategory.ZChaos, true) },
            { "zchaos_paper_mario", new("(ZChaos) Paper Mario", EffectCategory.ZChaos, true) },
            { "zchaos_large_player", new("(ZChaos) Large Player", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_player", new("(ZChaos) Tiny Player", EffectCategory.ZChaos, true) },
            { "zchaos_wide_player", new("(ZChaos) Wide Player", EffectCategory.ZChaos, true) },
            { "zchaos_very_wide_player", new("(ZChaos) Very Wide Player", EffectCategory.ZChaos, true) },
            { "zchaos_tall_player", new("(ZChaos) Tall Player", EffectCategory.ZChaos, true) },
            { "zchaos_long_player", new("(ZChaos) Long Player", EffectCategory.ZChaos, true) },
            { "zchaos_flat_player", new("(ZChaos) Flat Player", EffectCategory.ZChaos, true) },
            { "zchaos_reverse_player", new("(ZChaos) Reverse Player", EffectCategory.ZChaos, true) },
            { "zchaos_flipped_player", new("(ZChaos) Flipped Player", EffectCategory.ZChaos, true) },
            { "zchaos_nightmare_player", new("(ZChaos) Nightmare Player", EffectCategory.ZChaos, true) },
            { "zchaos_rolling_player", new("(ZChaos) Rolling Player", EffectCategory.ZChaos, true) },
            { "zchaos_spinning_player", new("(ZChaos) Spinning Player", EffectCategory.ZChaos, true) },
            { "zchaos_big_cars", new("(ZChaos) Big Cars", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_cars", new("(ZChaos) Tiny Cars", EffectCategory.ZChaos, true) },
            { "zchaos_hovering_cars", new("(ZChaos) Hovering Cars", EffectCategory.ZChaos, true) },
            { "zchaos_nightmare_cars", new("(ZChaos) Nightmare Cars", EffectCategory.ZChaos, true) },
            { "zchaos_paper_cars", new("(ZChaos) Paper Cars", EffectCategory.ZChaos, true) },
            { "zchaos_wide_cars", new("(ZChaos) Wide Cars", EffectCategory.ZChaos, true) },
            { "zchaos_very_wide_cars", new("(ZChaos) Very Wide Cars", EffectCategory.ZChaos, true) },
            { "zchaos_tall_cars", new("(ZChaos) Tall Cars", EffectCategory.ZChaos, true) },
            { "zchaos_long_cars", new("(ZChaos) Long Cars", EffectCategory.ZChaos, true) },
            { "zchaos_reverse_cars", new("(ZChaos) Reverse Cars", EffectCategory.ZChaos, true) },
            { "zchaos_flipped_cars", new("(ZChaos) Flipped Cars", EffectCategory.ZChaos, true) },
            { "zchaos_flat_cars", new("(ZChaos) Flat Cars", EffectCategory.ZChaos, true) },
            { "zchaos_c_h_o_n_k_y_cars", new("(ZChaos) C H O N K Y Cars", EffectCategory.ZChaos, true) },
            { "zchaos_rolling_cars", new("(ZChaos) Rolling Cars", EffectCategory.ZChaos, true) },
            { "zchaos_spinning_cars", new("(ZChaos) Spinning Cars", EffectCategory.ZChaos, true) },
            { "zchaos_large_peds", new("(ZChaos) Large Peds", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_peds", new("(ZChaos) Tiny Peds", EffectCategory.ZChaos, true) },
            { "zchaos_flipped_peds", new("(ZChaos) Flipped Peds", EffectCategory.ZChaos, true) },
            { "zchaos_paper_peds", new("(ZChaos) Paper Peds", EffectCategory.ZChaos, true) },
            { "zchaos_wide_peds", new("(ZChaos) Wide Peds", EffectCategory.ZChaos, true) },
            { "zchaos_very_wide_peds", new("(ZChaos) Very Wide Peds", EffectCategory.ZChaos, true) },
            { "zchaos_tall_peds", new("(ZChaos) Tall Peds", EffectCategory.ZChaos, true) },
            { "zchaos_long_peds", new("(ZChaos) Long Peds", EffectCategory.ZChaos, true) },
            { "zchaos_flat_peds", new("(ZChaos) Flat Peds", EffectCategory.ZChaos, true) },
            { "zchaos_reverse_peds", new("(ZChaos) Reverse Peds", EffectCategory.ZChaos, true) },
            { "zchaos_nightmare_peds", new("(ZChaos) Nightmare Peds", EffectCategory.ZChaos, true) },
            { "zchaos_rolling_peds", new("(ZChaos) Rolling Peds", EffectCategory.ZChaos, true) },
            { "zchaos_spinning_peds", new("(ZChaos) Spinning Peds", EffectCategory.ZChaos, true) },
            { "zchaos_no_traffic", new("(ZChaos) No Traffic", EffectCategory.ZChaos, true) },
            { "zchaos_phantom_traffic", new("(ZChaos) Phantom Traffic", EffectCategory.ZChaos, true) },
            { "zchaos_1_chance_of_death", new("(ZChaos) 1% chance of death", EffectCategory.ZChaos) },
            { "zchaos_earthquake_while_someones_playing_dubstep", new("(ZChaos) Earthquake while someone's playing dubstep", EffectCategory.ZChaos, true) },
            { "zchaos_rainbow_car_interiors", new("(ZChaos) Rainbow Car Interiors", EffectCategory.ZChaos, true) },
            { "zchaos_handbrake", new("(ZChaos) Handbrake", EffectCategory.ZChaos, true) },
            { "zchaos_blackout", new("(ZChaos) Blackout", EffectCategory.ZChaos, true) },
            { "zchaos_reinvent_the_wheel", new("(ZChaos) Reinvent the wheel", EffectCategory.ZChaos, true) },
            { "zchaos_gta_iv_car_interiors", new("(ZChaos) GTA IV Car Interiors", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_rhino", new("(ZChaos) Spawn Rhino", EffectCategory.ZChaos) },
            //{ "zchaos_spawn_rhino", new("(ZChaos) Spawn Rhino?", EffectCategory.ZChaos) },
            { "zchaos_ghost_cars", new("(ZChaos) Ghost Cars", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_to_mt_chilliad", new("(ZChaos) Teleport to Mt Chilliad", EffectCategory.ZChaos) },
            { "zchaos_teleport_to_mt_chilliad_tf", new("(ZChaos) Teleport to Mt Chilliad? :tf:", EffectCategory.ZChaos) },
            { "zchaos_random_weapon_upgrades", new("(ZChaos) Random Weapon Upgrades", EffectCategory.ZChaos) },
            { "zchaos_jimmy_you_little_shit", new("(ZChaos) JIMMY YOU LITTLE SHIT", EffectCategory.ZChaos, true) },
            { "zchaos_gta_online_radio_stations", new("(ZChaos) GTA Online Radio Stations", EffectCategory.ZChaos) },
            { "zchaos_collider_i_hardly_know_her", new("(ZChaos) Collider? I hardly know her", EffectCategory.ZChaos, true) },
            { "zchaos_no_shadows", new("(ZChaos) No Shadows", EffectCategory.ZChaos, true) },
            { "zchaos_gta_iv_car_camera", new("(ZChaos) GTA IV Car Camera", EffectCategory.ZChaos, true) },
            { "zchaos_you_control_every_car", new("(ZChaos) You Control Every Car", EffectCategory.ZChaos, true) },
            { "zchaos_absurd_car_deformation", new("(ZChaos) Absurd Car Deformation", EffectCategory.ZChaos, true) },
            { "zchaos_enable_crouching", new("(ZChaos) Enable Crouching", EffectCategory.ZChaos, true) },
            { "zchaos_no_visible_water", new("(ZChaos) No Visible Water", EffectCategory.ZChaos, true) },
            { "zchaos_corpa", new("(ZChaos) Corpa", EffectCategory.ZChaos, true) },
            { "zchaos_lock_all_cars", new("(ZChaos) Lock all Cars", EffectCategory.ZChaos, true) },
            { "zchaos_invisible_peds", new("(ZChaos) Invisible Peds", EffectCategory.ZChaos, true) },
            { "zchaos_faulty_gas_pedal", new("(ZChaos) Faulty Gas Pedal", EffectCategory.ZChaos, true) },
            { "zchaos_unlock_all_car_doors", new("(ZChaos) Unlock All Car Doors", EffectCategory.ZChaos, true) },
            { "zchaos_cruise_control", new("(ZChaos) Cruise Control", EffectCategory.ZChaos, true) },
            { "zchaos_tesla_mode", new("(ZChaos) Tesla Mode", EffectCategory.ZChaos, true) },
            { "zchaos_hope_you_picked_a_fwd", new("(ZChaos) Hope you picked a FWD", EffectCategory.ZChaos, true) },
            { "zchaos_x2_gravity", new("(ZChaos) X2 Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_alien_ray", new("(ZChaos) Alien Ray", EffectCategory.ZChaos, true) },
            { "zchaos_daytime", new("(ZChaos) Daytime", EffectCategory.ZChaos) },
            { "zchaos_nighttime", new("(ZChaos) Nighttime", EffectCategory.ZChaos) },
            { "zchaos_vehicle_ohko", new("(ZChaos) Vehicle OHKO", EffectCategory.ZChaos, true) },
            { "zchaos_global_vehicle_ohko", new("(ZChaos) Global Vehicle OHKO", EffectCategory.ZChaos, true) },
            { "zchaos_paper_buildings", new("(ZChaos) Paper Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_big_buildings", new("(ZChaos) Big Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_buildings", new("(ZChaos) Tiny Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_wide_buildings", new("(ZChaos) Wide Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_very_wide_buildings", new("(ZChaos) Very Wide Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_tall_buildings", new("(ZChaos) Tall Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_long_buildings", new("(ZChaos) Long Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_flat_buildings", new("(ZChaos) Flat Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_reverse_buildings", new("(ZChaos) Reverse Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_flipped_buildings", new("(ZChaos) Flipped Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_sideways_buildings", new("(ZChaos) Sideways Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_rolling_buildings", new("(ZChaos) Rolling Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_spinning_buildings", new("(ZChaos) Spinning Buildings", EffectCategory.ZChaos, true) },
            { "zchaos_paper_objects", new("(ZChaos) Paper Objects", EffectCategory.ZChaos, true) },
            { "zchaos_big_objects", new("(ZChaos) Big Objects", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_objects", new("(ZChaos) Tiny Objects", EffectCategory.ZChaos, true) },
            { "zchaos_wide_objects", new("(ZChaos) Wide Objects", EffectCategory.ZChaos, true) },
            { "zchaos_very_wide_objects", new("(ZChaos) Very Wide Objects", EffectCategory.ZChaos, true) },
            { "zchaos_tall_objects", new("(ZChaos) Tall Objects", EffectCategory.ZChaos, true) },
            { "zchaos_long_objects", new("(ZChaos) Long Objects", EffectCategory.ZChaos, true) },
            { "zchaos_flat_objects", new("(ZChaos) Flat Objects", EffectCategory.ZChaos, true) },
            { "zchaos_reverse_objects", new("(ZChaos) Reverse Objects", EffectCategory.ZChaos, true) },
            { "zchaos_flipped_objects", new("(ZChaos) Flipped Objects", EffectCategory.ZChaos, true) },
            { "zchaos_rolling_objects", new("(ZChaos) Rolling Objects", EffectCategory.ZChaos, true) },
            { "zchaos_spinning_objects", new("(ZChaos) Spinning Objects", EffectCategory.ZChaos, true) },
            { "zchaos_10x_car_gravity", new("(ZChaos) 10x Car Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_2x_car_gravity", new("(ZChaos) 2x Car Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_change_camera", new("(ZChaos) Change Camera", EffectCategory.ZChaos) },
            { "zchaos_rip_harder", new("(ZChaos) RIP HARDER", EffectCategory.ZChaos, true) },
            { "zchaos_random_tire_popping", new("(ZChaos) Random Tire Popping", EffectCategory.ZChaos, true) },
            { "zchaos_pop_one_tire", new("(ZChaos) Pop One Tire", EffectCategory.ZChaos) },
            { "zchaos_remove_one_tire", new("(ZChaos) Remove One Tire", EffectCategory.ZChaos, true) },
            { "zchaos_random_tire_dropping", new("(ZChaos) Random Tire Dropping", EffectCategory.ZChaos, true) },
            { "zchaos_euro_truck_simulator", new("(ZChaos) Euro Truck Simulator", EffectCategory.ZChaos) },
            { "zchaos_yellow_car", new("(ZChaos) YELLOW CAR", EffectCategory.ZChaos) },
            { "zchaos_rainy_weather", new("(ZChaos) Rainy Weather", EffectCategory.ZChaos) },
            { "zchaos_thunderstorm", new("(ZChaos) Thunderstorm", EffectCategory.ZChaos) },
            { "zchaos_hyper_sprint", new("(ZChaos) Hyper Sprint", EffectCategory.ZChaos, true) },
            { "zchaos_low_car_gravity", new("(ZChaos) Low Car Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_low_gravity", new("(ZChaos) Low Gravity", EffectCategory.ZChaos, true) },
            { "zchaos_no_shooting_allowed", new("(ZChaos) No Shooting Allowed", EffectCategory.ZChaos, true) },
            { "zchaos_shoutouts_to_simpleflips", new("(ZChaos) Shoutouts to SimpleFlips", EffectCategory.ZChaos, true) },
            { "zchaos_trans_rights", new("(ZChaos) Trans Rights", EffectCategory.ZChaos, true) },
            { "zchaos_buttsbot", new("(ZChaos) Buttsbot", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_tornado", new("(ZChaos) Spawn Tornado", EffectCategory.ZChaos, true) },
            { "zchaos_air_racing", new("(ZChaos) Air Racing", EffectCategory.ZChaos, true) },
            { "zchaos_tall_world", new("(ZChaos) Tall World", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_world", new("(ZChaos) Tiny World", EffectCategory.ZChaos, true) },
            { "zchaos_large_world", new("(ZChaos) Large World", EffectCategory.ZChaos, true) },
            { "zchaos_very_tall_world", new("(ZChaos) Very Tall World", EffectCategory.ZChaos, true) },
            { "zchaos_flat_world", new("(ZChaos) Flat World", EffectCategory.ZChaos, true) },
            { "zchaos_where_am_i", new("(ZChaos) WHERE AM I?!?!", EffectCategory.ZChaos, true) },
            { "zchaos_help", new("(ZChaos) help", EffectCategory.ZChaos, true) },
            { "zchaos_moving_world", new("(ZChaos) Moving World", EffectCategory.ZChaos, true) },
            { "zchaos_warping_world", new("(ZChaos) Warping World", EffectCategory.ZChaos, true) },
            { "zchaos_balloon_pedals", new("(ZChaos) Balloon Pedals", EffectCategory.ZChaos, true) },
            { "zchaos_dead_or_alive", new("(ZChaos) Dead or Alive", EffectCategory.ZChaos, true) },
            { "zchaos_swinging_car_doors", new("(ZChaos) Swinging Car Doors", EffectCategory.ZChaos, true) },
            { "zchaos_superhot", new("(ZChaos) SUPERHOT", EffectCategory.ZChaos, true) },
            { "zchaos_never_wanted", new("(ZChaos) Never Wanted", EffectCategory.ZChaos, true) },
            { "zchaos_destroy_car", new("(ZChaos) Destroy Car", EffectCategory.ZChaos) },
            { "zchaos_unlimited_ammo", new("(ZChaos) Unlimited Ammo", EffectCategory.ZChaos, true) },
            { "zchaos_whyd_you_leave_the_keys_upon_the", new("(ZChaos) Why'd you leave the keys upon the", EffectCategory.ZChaos) },
            { "zchaos_save_menu", new("(ZChaos) Save Menu", EffectCategory.ZChaos) },
            { "zchaos_mod_menu", new("(ZChaos) Mod Menu", EffectCategory.ZChaos, true) },
            { "zchaos_realistic_us_cops", new("(ZChaos) Realistic US Cops", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_dumptrucks", new("(ZChaos) Spawn Dumptrucks", EffectCategory.ZChaos, true) },
            { "zchaos_free_camera", new("(ZChaos) Free Camera", EffectCategory.ZChaos, true) },
            { "zchaos_everyone_hates_you", new("(ZChaos) Everyone Hates You", EffectCategory.ZChaos) },
            { "zchaos_everyone_really_hates_you", new("(ZChaos) Everyone REALLY Hates You", EffectCategory.ZChaos) },
            { "zchaos_launch_all_cars", new("(ZChaos) Launch All Cars", EffectCategory.ZChaos) },
            { "zchaos_give_sniper_rifle", new("(ZChaos) Give Sniper Rifle", EffectCategory.ZChaos) },
            { "zchaos_launch_car_into_the_stratosphere", new("(ZChaos) Launch Car into the Stratosphere", EffectCategory.ZChaos, true) },
            { "zchaos_san_andreas_car_camera", new("(ZChaos) San Andreas Car Camera", EffectCategory.ZChaos, true) },
            { "zchaos_wirtual_mode", new("(ZChaos) Wirtual Mode", EffectCategory.ZChaos, true) },
            { "zchaos_big_weapons", new("(ZChaos) Big Weapons", EffectCategory.ZChaos, true) },
            { "zchaos_tiny_weapons", new("(ZChaos) Tiny Weapons", EffectCategory.ZChaos, true) },
            { "zchaos_randomize_all_text", new("(ZChaos) Randomize All Text", EffectCategory.ZChaos, true) },
            { "zchaos_pphop", new("(ZChaos) ppHop", EffectCategory.ZChaos, true) },
            { "zchaos_hyper_gravity_field", new("(ZChaos) Hyper Gravity Field", EffectCategory.ZChaos, true) },
            { "zchaos_random_game_speed", new("(ZChaos) Random Game Speed", EffectCategory.ZChaos, true) },
            { "zchaos_wide_weapons", new("(ZChaos) Wide Weapons", EffectCategory.ZChaos, true) },
            { "zchaos_strong_wind", new("(ZChaos) Strong Wind", EffectCategory.ZChaos, true) },
            { "zchaos_which_way_do_i_go_again", new("(ZChaos) Which way do I go again?", EffectCategory.ZChaos, true) },
            { "zchaos_reverse_forcefield", new("(ZChaos) Reverse Forcefield", EffectCategory.ZChaos, true) },
            { "zchaos_magnet_cars", new("(ZChaos) Magnet Cars", EffectCategory.ZChaos, true) },
            { "zchaos_floating_point_inaccuracy", new("(ZChaos) Floating Point Inaccuracy", EffectCategory.ZChaos, true) },
            { "zchaos_8_bit_steering", new("(ZChaos) 8 Bit Steering", EffectCategory.ZChaos, true) },
            { "zchaos_extreme_floating_point_inaccuracy", new("(ZChaos) Extreme Floating Point Inaccuracy", EffectCategory.ZChaos, true) },
            { "zchaos_hover_cars", new("(ZChaos) Hover Cars", EffectCategory.ZChaos, true) },
            { "zchaos_uwuify", new("(ZChaos) UwUify", EffectCategory.ZChaos, true) },
            { "zchaos_familiar_chaos_ui", new("(ZChaos) Familiar Chaos UI", EffectCategory.ZChaos, true) },
            { "zchaos_vehicular_bullets", new("(ZChaos) Vehicular Bullets", EffectCategory.ZChaos, true) },
            { "zchaos_jenga", new("(ZChaos) Jenga", EffectCategory.ZChaos, true) },
            { "zchaos_create_radar_blip", new("(ZChaos) Create Radar Blip", EffectCategory.ZChaos) },
            { "zchaos_create_large_radar_blip", new("(ZChaos) Create Large Radar Blip", EffectCategory.ZChaos) },
            { "zchaos_give_everyone_miniguns", new("(ZChaos) Give Everyone Miniguns", EffectCategory.ZChaos) },
            { "zchaos_give_all_peds_miniguns", new("(ZChaos) Give All Peds Miniguns", EffectCategory.ZChaos) },
            { "zchaos_attach_nearest_ped_to_you", new("(ZChaos) Attach Nearest Ped to You", EffectCategory.ZChaos, true) },
            { "zchaos_windows_98_hud", new("(ZChaos) Windows 98 HUD", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_100_beach_balls", new("(ZChaos) Spawn 100 Beach Balls", EffectCategory.ZChaos) },
            { "zchaos_beach_ball_jail", new("(ZChaos) Beach Ball Jail", EffectCategory.ZChaos) },
            { "zchaos_become_a_bouncy_ball", new("(ZChaos) Become a Bouncy Ball", EffectCategory.ZChaos, true) },
            { "zchaos_car_godmode", new("(ZChaos) Car Godmode", EffectCategory.ZChaos, true) },
            { "zchaos_zoomed_in_radar", new("(ZChaos) Zoomed In Radar", EffectCategory.ZChaos, true) },
            { "zchaos_godmode_for_everyone", new("(ZChaos) Godmode for Everyone", EffectCategory.ZChaos, true) },
            { "zchaos_all_this_shit_paid_for_with_bad_credit", new("(ZChaos) All this shit paid for with bad credit", EffectCategory.ZChaos, true) },
            { "zchaos_give_minigun", new("(ZChaos) Give Minigun", EffectCategory.ZChaos) },
            { "zchaos_rolling_camera", new("(ZChaos) Rolling Camera", EffectCategory.ZChaos, true) },
            { "zchaos_spinning_camera", new("(ZChaos) Spinning Camera", EffectCategory.ZChaos, true) },
            { "zchaos_deforestation", new("(ZChaos) Deforestation", EffectCategory.ZChaos, true) },
            { "zchaos_neko_text", new("(ZChaos) Neko Text", EffectCategory.ZChaos, true) },
            { "zchaos_tilted_camera", new("(ZChaos) Tilted Camera", EffectCategory.ZChaos, true) },
            { "zchaos_sideways_camera", new("(ZChaos) Sideways Camera", EffectCategory.ZChaos, true) },
            { "zchaos_slow_bleeding", new("(ZChaos) Slow Bleeding", EffectCategory.ZChaos, true) },
            { "zchaos_heavy_weapon_recoil", new("(ZChaos) Heavy Weapon Recoil", EffectCategory.ZChaos, true) },
            { "zchaos_teleport__no_pausing__l__ratio", new("(ZChaos) Teleport + No Pausing + L + Ratio", EffectCategory.ZChaos, true) },
            { "zchaos_mitosis_on_ped_death", new("(ZChaos) Mitosis on Ped Death", EffectCategory.ZChaos, true) },
            { "zchaos_not_shown_to_streamer_8_minute_fadeout", new("(ZChaos) [Not shown to streamer] 8 Minute Fadeout", EffectCategory.ZChaos, true) },
            { "zchaos_to_be_continued", new("(ZChaos) To Be Continued", EffectCategory.ZChaos, true) },
            { "zchaos_ohio", new("(ZChaos) Ohio", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_all_vehicles_to_you", new("(ZChaos) Teleport All Vehicles to You", EffectCategory.ZChaos) },
            { "zchaos_quakehalf-life_movement", new("(ZChaos) Quake/Half-Life Movement", EffectCategory.ZChaos, true) },
            { "zchaos_teleport_to_random_vehicle", new("(ZChaos) Teleport to Random Vehicle", EffectCategory.ZChaos) },
            { "zchaos_traffic_explodes_when_hit", new("(ZChaos) Traffic Explodes when Hit", EffectCategory.ZChaos, true) },
            { "zchaos_blinking_cars", new("(ZChaos) Blinking Cars", EffectCategory.ZChaos, true) },
            { "zchaos_no_healing__health_regen", new("(ZChaos) No Healing & Health Regen", EffectCategory.ZChaos, true) },
            { "zchaos_griefer_jesus_info_display", new("(ZChaos) Griefer Jesus Info Display", EffectCategory.ZChaos, true) },
            { "zchaos_its_raining_men", new("(ZChaos) It's Raining Men", EffectCategory.ZChaos, true) },
            { "zchaos_rotatory_engines", new("(ZChaos) Rota(to)ry Engines", EffectCategory.ZChaos, true) },
            { "zchaos_borpaspin", new("(ZChaos) borpaSpin", EffectCategory.ZChaos, true) },
            { "zchaos_global_car_godmode", new("(ZChaos) Global Car Godmode", EffectCategory.ZChaos, true) },
            { "zchaos_kill_all_nearby_peds", new("(ZChaos) Kill All Nearby Peds", EffectCategory.ZChaos) },
            { "zchaos_up__down", new("(ZChaos) Up & Down", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_griefer_jesus", new("(ZChaos) Spawn Griefer Jesus", EffectCategory.ZChaos) },
            { "zchaos_spawn_extreme_griefer_jesus", new("(ZChaos) Spawn Extreme Griefer Jesus", EffectCategory.ZChaos) },
            { "zchaos_teleport_to_griefer_jesus", new("(ZChaos) Teleport to Griefer Jesus", EffectCategory.ZChaos) },
            { "zchaos_heavy_snowfall", new("(ZChaos) Heavy Snowfall", EffectCategory.ZChaos, true) },
            { "zchaos_no_rendering", new("(ZChaos) No Rendering?", EffectCategory.ZChaos, true) },
            { "zchaos_fuck_up_world", new("(ZChaos) Fuck Up World", EffectCategory.ZChaos, true) },
            { "zchaos_pepega_world", new("(ZChaos) Pepega World", EffectCategory.ZChaos, true) },
            { "zchaos_unaware", new("(ZChaos) Unaware", EffectCategory.ZChaos, true) },
            { "zchaos_its_morbin_time", new("(ZChaos) It's Morbin' Time", EffectCategory.ZChaos, true) },
            { "zchaos_forgot_to_install_css", new("(ZChaos) Forgot to install CS:S", EffectCategory.ZChaos, true) },
            { "zchaos_gigachad", new("(ZChaos) GIGACHAD", EffectCategory.ZChaos, true) },
            { "zchaos_wireframe_mode", new("(ZChaos) Wireframe Mode", EffectCategory.ZChaos, true) },
            { "zchaos_mirrored", new("(ZChaos) Mirrored", EffectCategory.ZChaos, true) },
            { "zchaos_mirrored_hud", new("(ZChaos) Mirrored HUD", EffectCategory.ZChaos, true) },
            { "zchaos_gta_iv_vehicle_handling", new("(ZChaos) GTA IV Vehicle Handling", EffectCategory.ZChaos, true) },
            { "zchaos_caveman_weapons", new("(ZChaos) Caveman Weapons", EffectCategory.ZChaos, true) },
            { "zchaos_we_have_chase_camera_at_home", new("(ZChaos) We have Chase Camera at home", EffectCategory.ZChaos, true) },
            { "zchaos_metal_pipes", new("(ZChaos) Metal Pipes", EffectCategory.ZChaos, true) },
            { "zchaos_big_heads", new("(ZChaos) Big Heads", EffectCategory.ZChaos, true) },
            { "zchaos_hold_the_fuck_up", new("(ZChaos) Hold The Fuck Up", EffectCategory.ZChaos, true) },
            { "zchaos_waytoodank", new("(ZChaos) WAYTOODANK", EffectCategory.ZChaos, true) },
            { "zchaos_big_slappy", new("(ZChaos) Big Slappy", EffectCategory.ZChaos, true) },
            { "zchaos_cost_an_arm_and_a_leg", new("(ZChaos) Cost an Arm and a Leg", EffectCategory.ZChaos, true) },
            { "zchaos_mission_failed", new("(ZChaos) Mission Failed", EffectCategory.ZChaos) },
            { "zchaos_forced_geoguessr", new("(ZChaos) Forced Geoguessr", EffectCategory.ZChaos, true) },
            { "zchaos_charred_car_skin", new("(ZChaos) Charred Car Skin", EffectCategory.ZChaos, true) },
            { "zchaos_big_rigs_handling", new("(ZChaos) Big Rigs Handling", EffectCategory.ZChaos, true) },
            { "zchaos_hesoyam", new("(ZChaos) HESOYAM", EffectCategory.ZChaos) },
            { "zchaos_set_gps_route_to_large_radar_blip", new("(ZChaos) Set GPS Route to Large Radar Blip", EffectCategory.ZChaos) },
            { "zchaos_forced_distribution", new("(ZChaos) Forced Distribution", EffectCategory.ZChaos) },
            { "zchaos_reset_distribution_deals", new("(ZChaos) Reset Distribution Deals", EffectCategory.ZChaos) },
            { "zchaos_add_one_distribution_deal", new("(ZChaos) Add One Distribution Deal", EffectCategory.ZChaos) },
            { "zchaos_add_two_distribution_deals", new("(ZChaos) Add Two Distribution Deals", EffectCategory.ZChaos) },
            { "zchaos_minigame_distribution_lite", new("(ZChaos) Minigame: Distribution Lite", EffectCategory.ZChaos) },
            { "zchaos_suspend_mission_flow", new("(ZChaos) Suspend Mission Flow", EffectCategory.ZChaos, true) },
            { "zchaos_remove_one_large_radar_blip", new("(ZChaos) Remove One Large Radar Blip", EffectCategory.ZChaos) },
            { "zchaos_pills_here", new("(ZChaos) PILLS HERE", EffectCategory.ZChaos) },
            { "zchaos_reset_effect_cycle", new("(ZChaos) Reset Effect Cycle", EffectCategory.ZChaos) },
            { "zchaos_subnautica", new("(ZChaos) Subnautica", EffectCategory.ZChaos, true) },
            { "zchaos_create_large_radar_blip_somewhere", new("(ZChaos) Create Large Radar Blip... somewhere", EffectCategory.ZChaos) },
            { "zchaos_create_5_large_radar_blips_somewhere", new("(ZChaos) Create 5 Large Radar Blips... somewhere", EffectCategory.ZChaos) },
            { "zchaos_iui_uiu", new("(ZChaos) i?u?i u?i?u", EffectCategory.ZChaos, true) },
            { "zchaos_minigame_insurance_fraud", new("(ZChaos) Minigame: Insurance Fraud", EffectCategory.ZChaos) },
            { "zchaos_titan", new("(ZChaos) Titan", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_a_pole_next_time_you_drive_fast", new("(ZChaos) Spawn a pole next time you drive fast", EffectCategory.ZChaos) },
            { "zchaos_spawn_a_pole_next_time_you_fly_a_plane", new("(ZChaos) Spawn a pole next time you fly a plane", EffectCategory.ZChaos) },
            { "zchaos_jesus_reacts", new("(ZChaos) Jesus Reacts", EffectCategory.ZChaos, true) },
            { "zchaos_chat_controls_tetris", new("(ZChaos) Chat Controls Tetris", EffectCategory.ZChaos) },
            { "zchaos_one", new("(ZChaos) ONE", EffectCategory.ZChaos) },
            { "zchaos_suavemente", new("(ZChaos) SUAVEMENTE", EffectCategory.ZChaos, true) },
            { "zchaos_kill_jack_benton", new("(ZChaos) Kill Jack Benton", EffectCategory.ZChaos, true) },
            { "zchaos_memz", new("(ZChaos) MEMZ", EffectCategory.ZChaos, true) },
            { "zchaos_metallic_gearbox", new("(ZChaos) Metallic Gearbox", EffectCategory.ZChaos, true) },
            { "zchaos_increase_large_radar_blip_size", new("(ZChaos) Increase Large Radar Blip Size", EffectCategory.ZChaos) },
            { "zchaos_decrease_large_radar_blip_size", new("(ZChaos) Decrease Large Radar Blip Size", EffectCategory.ZChaos) },
            { "zchaos_reset_large_radar_blip_size", new("(ZChaos) Reset Large Radar Blip Size", EffectCategory.ZChaos) },
            { "zchaos_detach_cars_grip_on_reality", new("(ZChaos) Detach Car's Grip on Reality", EffectCategory.ZChaos, true) },
            { "zchaos_theres_something_wrong_with_your_ride", new("(ZChaos) There's something wrong with your ride", EffectCategory.ZChaos, true) },
            { "zchaos_spawn_immortal_snail_jesus_somewhere", new("(ZChaos) Spawn Immortal Snail Jesus... somewhere", EffectCategory.ZChaos) },
            { "zchaos_teleport_one_immortal_snail_jesus_somewhere_else", new("(ZChaos) Teleport One Immortal Snail Jesus Somewhere Else", EffectCategory.ZChaos) },
            { "zchaos_griefer_jesus_radar_blips", new("(ZChaos) Griefer Jesus Radar Blips", EffectCategory.ZChaos, true) },
            { "zchaos_car_crusher_bug", new("(ZChaos) Car Crusher Bug", EffectCategory.ZChaos, true) },
            { "zchaos_blue_cheese", new("(ZChaos) Blue Cheese", EffectCategory.ZChaos, true) },
        };
    }
}
