#pragma once

#include "Memory/Entity.h"

#include "Util/Hash.h"

#include "EntityIterator.h"

#include "Memory/WorldToScreen.h"

const inline std::set<Hash> treeModels = {
	"prop_veg_crop_tr_02"_hash,
	"prop_coral_flat_02"_hash,
	"prop_log_break_01"_hash,
	"prop_coral_spikey_01"_hash,
	"prop_veg_crop_03_pump"_hash,
	"prop_coral_flat_brainy"_hash,
	"prop_coral_pillar_01"_hash,
	"prop_cora_clam_01"_hash,
	"prop_coral_sweed_02"_hash,
	"prop_coral_kelp_01_l1"_hash,
	"prop_coral_kelp_03d"_hash,
	"prop_sea_rubprox_01"_hash,
	"prop_coral_kelp_03c"_hash,
	"prop_coral_kelp_03_l1"_hash,
	"prop_coral_kelp_02_l1"_hash,
	"prop_veg_crop_05"_hash,
	"prop_coral_sweed_01"_hash,
	"prop_veg_crop_orange"_hash,
	"prop_coral_kelp_04"_hash,
	"prop_veg_crop_01"_hash,
	"prop_coral_kelp_03a"_hash,
	"prop_coral_kelp_03b"_hash,
	"prop_bush_grape_01"_hash,
	"prop_coral_flat_01_l1"_hash,
	"prop_coral_kelp_02"_hash,
	"prop_veg_crop_02"_hash,
	"prop_veg_crop_04"_hash,
	"prop_veg_crop_03_cab"_hash,
	"prop_coral_sweed_03"_hash,
	"prop_coral_stone_03"_hash,
	"prop_coral_bush_01"_hash,
	"prop_tree_birch_05"_hash,
	"prop_coral_kelp_04_l1"_hash,
	"prop_coral_flat_clam"_hash,
	"prop_coral_kelp_03"_hash,
	"prop_coral_grass_02"_hash,
	"prop_veg_crop_04_leaf"_hash,
	"prop_coral_grass_01"_hash,
	"prop_veg_crop_tr_01"_hash,
	"prop_coral_stone_04"_hash,
	"prop_coral_pillar_02"_hash,
	"prop_veg_corn_01"_hash,
	"prop_coral_sweed_04"_hash,
	"prop_coral_flat_01"_hash,
	"prop_coral_kelp_01"_hash,
	"prop_veg_crop_06"_hash,
	"prop_palm_fan_04_c"_hash,
	"prop_palm_fan_02_a"_hash,
	"prop_palm_fan_03_d_graff"_hash,
	"prop_palm_fan_03_b"_hash,
	"prop_palm_fan_03_c"_hash,
	"prop_palm_huge_01b"_hash,
	"prop_palm_fan_04_d"_hash,
	"prop_palm_huge_01a"_hash,
	"prop_palm_fan_04_b"_hash,
	"prop_palm_fan_03_c_graff"_hash,
	"prop_palm_fan_02_b"_hash,
	"prop_palm_fan_03_a"_hash,
	"prop_fan_palm_01a"_hash,
	"prop_palm_fan_03_d"_hash,
	"sd_palm10_low_uv"_hash,
	"prop_palm_fan_04_a"_hash,
	"prop_plant_flower_01"_hash,
	"prop_aloevera_01"_hash,
	"prop_veg_grass_01_b"_hash,
	"prop_plant_clover_01"_hash,
	"prop_plant_palm_01b"_hash,
	"prop_plant_paradise_b"_hash,
	"prop_plant_fern_02b"_hash,
	"prop_veg_grass_01_c"_hash,
	"prop_bush_dead_02"_hash,
	"prop_veg_grass_01_a"_hash,
	"prop_cat_tail_01"_hash,
	"prop_plant_cane_01b"_hash,
	"reeds_03"_hash,
	"prop_plant_cane_02b"_hash,
	"prop_p_spider_01d"_hash,
	"prop_plant_cane_02a"_hash,
	"prop_agave_01"_hash,
	"prop_grass_dry_03"_hash,
	"prop_plant_fern_02c"_hash,
	"prop_cs_plant_01"_hash,
	"prop_plant_cane_01a"_hash,
	"prop_plant_fern_01a"_hash,
	"prop_plant_01a"_hash,
	"prop_plant_fern_01b"_hash,
	"prop_plant_palm_01a"_hash,
	"prop_p_spider_01c"_hash,
	"prop_plant_flower_03"_hash,
	"prop_plant_clover_02"_hash,
	"prop_plant_flower_04"_hash,
	"prop_agave_02"_hash,
	"prop_veg_grass_01_d"_hash,
	"prop_p_spider_01a"_hash,
	"prop_plant_palm_01c"_hash,
	"prop_plant_paradise"_hash,
	"prop_plant_01b"_hash,
	"prop_grass_dry_02"_hash,
	"prop_plant_base_01"_hash,
	"prop_veg_grass_02_a"_hash,
	"prop_plant_flower_02"_hash,
	"prop_plant_base_02"_hash,
	"prop_plant_base_03"_hash,
	"prop_plant_fern_02a"_hash,
	"prop_palm_med_01d"_hash,
	"prop_palm_med_01c"_hash,
	"prop_palm_sm_01f"_hash,
	"prop_palm_med_01a"_hash,
	"prop_palm_sm_01d"_hash,
	"prop_palm_sm_01a"_hash,
	"prop_palm_med_01b"_hash,
	"prop_palm_sm_01e"_hash,
	"prop_tree_olive_01"_hash,
	"prop_rio_del_01"_hash,
	"prop_tree_fallen_02"_hash,
	"prop_rus_olive_wint"_hash,
	"prop_tree_eucalip_01"_hash,
	"prop_tree_pine_02"_hash,
	"prop_tree_birch_03"_hash,
	"prop_tree_pine_01"_hash,
	"prop_tree_stump_01"_hash,
	"prop_tree_eng_oak_creator"_hash,
	"prop_tree_lficus_06"_hash,
	"prop_tree_lficus_05"_hash,
	"prop_tree_fallen_pine_01"_hash,
	"prop_w_r_cedar_dead"_hash,
	"prop_tree_maple_02"_hash,
	"prop_tree_eng_oak_01"_hash,
	"prop_rus_olive_l2"_hash,
	"prop_tree_fallen_01"_hash,
	"prop_tree_birch_04"_hash,
	"prop_tree_mquite_01"_hash,
	"prop_tree_maple_03"_hash,
	"prop_w_r_cedar_01"_hash,
	"prop_tree_olive_creator"_hash,
	"prop_tree_birch_01"_hash,
	"test_tree_forest_trunk_base_01"_hash,
	"prop_tree_cedar_s_06"_hash,
	"test_tree_forest_trunk_01"_hash,
	"prop_tree_cedar_s_02"_hash,
	"prop_tree_cedar_s_01"_hash,
	"test_tree_forest_trunk_04"_hash,
	"prop_s_pine_dead_01"_hash,
	"prop_tree_jacada_02"_hash,
	"prop_tree_log_02"_hash,
	"test_tree_cedar_trunk_001"_hash,
	"prop_rio_del_01_l3"_hash,
	"prop_tree_jacada_01"_hash,
	"prop_tree_lficus_03"_hash,
	"prop_tree_cedar_s_04"_hash,
	"prop_tree_cedar_02"_hash,
	"prop_tree_lficus_02"_hash,
	"prop_tree_birch_03b"_hash,
	"prop_tree_cedar_03"_hash,
	"prop_rus_olive"_hash,
	"test_tree_forest_trunk_fall_01"_hash,
	"prop_tree_oak_01"_hash,
	"prop_tree_cedar_s_05"_hash,
	"prop_tree_cedar_04"_hash,
	"prop_tree_cypress_01"_hash,
	"prop_tree_birch_02"_hash,
	"prop_tree_log_01"_hash,
	"prop_tree_mquite_01_l2"_hash,
	"hei_prop_hei_tree_fallen_02"_hash,
	"prop_sapling_break_01"_hash,
	"prop_sapling_break_02"_hash,
	"prop_tree_eng_oak_cr2"_hash,
	"prop_tree_olive_cr2"_hash,
	"prop_xmas_ext"_hash,
	"prop_weeddry_nxg03b"_hash,
	"prop_bush_med_01"_hash,
	"prop_bush_lrg_01b"_hash,
	"prop_weeds_nxg08"_hash,
	"prop_weeds_nxg05b"_hash,
	"prop_weeddry_nxg02"_hash,
	"prop_bush_ivy_02_1m"_hash,
	"prop_plant_group_06c"_hash,
	"prop_bush_ivy_01_top"_hash,
	"prop_bush_ornament_01"_hash,
	"prop_bush_med_06"_hash,
	"prop_weeddry_nxg04"_hash,
	"prop_weeds_nxg01"_hash,
	"prop_weeds_nxg04"_hash,
	"prop_bush_med_05"_hash,
	"prop_bush_lrg_03"_hash,
	"prop_plant_group_04_cr"_hash,
	"prop_bush_ivy_01_1m"_hash,
	"prop_bush_lrg_01c"_hash,
	"prop_bush_lrg_04c"_hash,
	"prop_weeddry_nxg01"_hash,
	"prop_bush_lrg_01c_cr"_hash,
	"prop_weeds_nxg09"_hash,
	"prop_weeds_nxg06b"_hash,
	"prop_desert_iron_01"_hash,
	"prop_weeds_nxg04b"_hash,
	"prop_creosote_b_01"_hash,
	"prop_weeds_nxg07b"_hash,
	"prop_bush_lrg_01d"_hash,
	"prop_bush_ornament_02"_hash,
	"prop_bush_ivy_02_2m"_hash,
	"prop_plant_group_02"_hash,
	"prop_weeds_nxg01b"_hash,
	"prop_bush_neat_06"_hash,
	"prop_plant_group_06a"_hash,
	"prop_plant_group_05e"_hash,
	"prop_bush_neat_07"_hash,
	"prop_bush_ivy_02_pot"_hash,
	"prop_bush_ivy_01_r"_hash,
	"prop_weeddry_nxg03"_hash,
	"prop_weeds_nxg06"_hash,
	"prop_plant_group_05c"_hash,
	"prop_bush_med_03"_hash,
	"prop_bush_neat_01"_hash,
	"prop_skunk_bush_01"_hash,
	"prop_bush_neat_03"_hash,
	"prop_plant_group_05b"_hash,
	"prop_bush_ornament_04"_hash,
	"prop_bush_lrg_04d"_hash,
	"prop_bush_ivy_02_top"_hash,
	"prop_weeds_nxg03b"_hash,
	"prop_weeddead_nxg01"_hash,
	"prop_weeds_nxg02b"_hash,
	"prop_bush_ivy_02_r"_hash,
	"prop_weeddead_nxg02"_hash,
	"prop_plant_group_03"_hash,
	"prop_weeddry_nxg01b"_hash,
	"prop_bush_neat_04"_hash,
	"prop_weeds_nxg07b001"_hash,
	"prop_bush_neat_08"_hash,
	"prop_bush_lrg_02"_hash,
	"prop_weeddry_nxg05"_hash,
	"prop_bush_lrg_01e"_hash,
	"prop_plant_group_05"_hash,
	"prop_weeddry_nxg02b"_hash,
	"prop_bush_lrg_01"_hash,
	"prop_bush_ivy_01_pot"_hash,
	"prop_bush_lrg_04b"_hash,
	"prop_bush_ivy_01_bk"_hash,
	"prop_bush_neat_02"_hash,
	"prop_bush_lrg_01e_cr"_hash,
	"prop_weeds_nxg03"_hash,
	"prop_weeds_nxg02"_hash,
	"prop_plant_group_06b"_hash,
	"prop_am_box_wood_01"_hash,
	"prop_bush_neat_05"_hash,
	"prop_bush_med_03_cr"_hash,
	"prop_bush_ivy_02_l"_hash,
	"prop_bush_ornament_03"_hash,
	"prop_bush_ivy_01_2m"_hash,
	"prop_plant_group_01"_hash,
	"prop_bush_lrg_02b"_hash,
	"prop_weeds_nxg08b"_hash,
	"prop_plant_group_04"_hash,
	"prop_bush_ivy_01_l"_hash,
	"prop_plant_group_05d"_hash,
	"prop_bush_med_07"_hash,
	"prop_weeds_nxg05"_hash,
	"prop_bush_med_02"_hash,
	"proc_lupins_01"_hash,
	"proc_drygrasses01b"_hash,
	"prop_grass_ca"_hash,
	"proc_leafyplant_01"_hash,
	"proc_desert_sage_01"_hash,
	"proc_grassdandelion01"_hash,
	"prop_log_ab"_hash,
	"v_proc2_temp"_hash,
	"urbanweeds01_l1"_hash,
	"proc_stones_05"_hash,
	"proc_stones_06"_hash,
	"proc_grasses01"_hash,
	"prop_log_aa"_hash,
	"prop_log_ad"_hash,
	"proc_forest_ivy_01"_hash,
	"proc_sage_01"_hash,
	"prop_log_ac"_hash,
	"urbanweeds02_l1"_hash,
	"prop_weed_002_ba"_hash,
	"proc_scrub_bush01"_hash,
	"proc_stones_01"_hash,
	"prop_saplin_001_c"_hash,
	"prop_dandy_b"_hash,
	"ng_proc_temp"_hash,
	"proc_indian_pbrush_01"_hash,
	"proc_dry_plants_01"_hash,
	"prop_fernbb"_hash,
	"proc_grassplantmix_02"_hash,
	"prop_thindesertfiller_aa"_hash,
	"proc_sml_reeds_01c"_hash,
	"urbangrnfrnds_01"_hash,
	"prop_grass_da"_hash,
	"proc_forest_grass01"_hash,
	"proc_lizardtail_01"_hash,
	"proc_sml_reeds_01b"_hash,
	"proc_stones_03"_hash,
	"proc_stones_02"_hash,
	"prop_flowerweed_005_a"_hash,
	"proc_dryplantsgrass_01"_hash,
	"prop_log_af"_hash,
	"urbanweeds02"_hash,
	"proc_grasses01b"_hash,
	"urbangrngrass_01"_hash,
	"proc_stones_04"_hash,
	"proc_meadowmix_01"_hash,
	"proc_meadowpoppy_01"_hash,
	"prop_grass_001_a"_hash,
	"urbanweeds01"_hash,
	"proc_drygrasses01"_hash,
	"proc_dryplantsgrass_02"_hash,
	"prop_log_ae"_hash,
	"prop_tall_grass_ba"_hash,
	"prop_saplin_002_b"_hash,
	"prop_saplin_002_c"_hash,
	"proc_grassplantmix_01"_hash,
	"urbandryfrnds_01"_hash,
	"prop_saplin_001_b"_hash,
	"prop_dryweed_001_a"_hash,
	"prop_dryweed_002_a"_hash,
	"prop_fernba"_hash,
	"proc_leafybush_01"_hash,
	"prop_tall_drygrass_aa"_hash,
	"proc_sml_reeds_01"_hash,
	"urbandrygrass_01"_hash,
	"proc_wildquinine"_hash,
	"proc_drygrassfronds01"_hash,
	"prop_fem_01"_hash,
	"prop_weed_001_aa"_hash,
	"proc_brittlebush_01"_hash,
	"proc_grassfronds01"_hash,
	"prop_small_bushyba"_hash,
	"prop_joshua_tree_02c"_hash,
	"prop_cactus_01a"_hash,
	"prop_joshua_tree_01b"_hash,
	"prop_joshua_tree_02d"_hash,
	"prop_cactus_03"_hash,
	"prop_joshua_tree_01a"_hash,
	"prop_cactus_01d"_hash,
	"prop_joshua_tree_01e"_hash,
	"prop_joshua_tree_01d"_hash,
	"prop_cactus_01c"_hash,
	"prop_joshua_tree_01c"_hash,
	"prop_cactus_02"_hash,
	"prop_cactus_01e"_hash,
	"prop_joshua_tree_02b"_hash,
	"prop_joshua_tree_02a"_hash,
	"prop_cactus_01b"_hash,
	"prop_joshua_tree_02e"_hash,
};

inline auto GetAllVisibleBuildings()
{
	std::vector<Entity> arr;

	const auto playerPos = GET_ENTITY_COORDS(PLAYER_PED_ID(), false);

	const auto process   = [&playerPos, &arr](Entity building)
	{
		auto model = Memory::GetEntityModel(building);

		if (model)
		{
			auto coords = GET_ENTITY_COORDS(building, false);
			Vector3 min, max;
			GET_MODEL_DIMENSIONS(model, &min, &max);

			const auto radius =
			    std::max(std::abs(max.x - min.x), std::max(std::abs(max.y - min.y), std::abs(max.z - min.z)));

			if (radius / coords.DistanceTo(playerPos) > 0.02f
			    && IS_SPHERE_VISIBLE(coords.x, coords.y, coords.z, radius))
				arr.push_back(building);
		}
	};

	for (const auto building : GetAllBuildings())
		process(building);

	for (const auto building : GetAllAnimatedBuildings())
		process(building);

	for (const auto building : GetAllGrass())
		process(building);

	return arr;
}

inline auto GetAllTrees()
{
	std::vector<Entity> arr;

	for (const auto building : GetAllVisibleBuildings())
	{
		auto model = Memory::GetEntityModel(building);

		if (model && treeModels.contains(model))
			arr.push_back(building);
	}

	return arr;
}
