name: Compile

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
    - uses: actions/checkout@v4

    - name: Setup
      run: git submodule update --init --recursive

    - name: Compile ASI & Dependencies
      run: |
        cd ChaosMod
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE="Release" -DWITH_DEBUG_PANEL_SUPPORT=1 ../
        ninja

    - name: Get NuGet Packages
      run: msbuild ChaosMod.sln /t:restore /p:RestorePackagesConfig=true /p:Configuration=Release

    - name: Compile Config App
      run: dotnet publish ConfigApp -c Release

    - name: Compile Voting Proxy
      run: dotnet publish TwitchChatVotingProxy -c Release

    - name: Compile Voting Overlay
      run: |
        cd twitchVotingOverlay
        npm install
        npm run compile:prod

    - name: Generate Native Definitions for Lua Runtime
      run: |
        cd scripts
        python generate_natives.py

    - name: Ready up for distribution
      run: |
        mkdir dist
        cd dist
        C:\msys64\usr\bin\wget.exe http://gopong.dev/chaos/data.zip
        7z.exe x data.zip
        rm data.zip
        cp ../ChaosMod/build/ChaosMod.asi
        cp ../ConfigApp/bin/x64/Release/net9.0-windows/win-x64/publish/ChaosModVConfig.exe chaosmod/
        cp ../TwitchChatVotingProxy/bin/x64/Release/net9.0-windows/win-x64/publish/TwitchChatVotingProxy.exe chaosmod/
        cp -r ../twitchVotingOverlay/dist chaosmod/twitchOverlay
        cp ../scripts/natives_def.lua chaosmod/
        cd ..
        mkdir symbols
        cd symbols
        cp ../ChaosMod/build/ChaosMod.pdb
        cp ../ConfigApp/bin/x64/Release/net9.0-windows/win-x64/publish/ChaosModVConfig.pdb
        cp ../TwitchChatVotingProxy/bin/x64/Release/net9.0-windows/win-x64/publish/TwitchChatVotingProxy.pdb
        cd ..

    - name: Copy files to Inno source folder
      run: |
        c:\windows\system32\xcopy.exe "dist\" "Installer\" /S /E /I /Y

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: Installer/install.iss
        options: /O+

    - name: Upload :)
      uses: actions/upload-artifact@v4
      with:
        name: chaosmod
        path: dist
    
    - name: Upload installer :)
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: Installer/dst/ChaosModInstaller.exe

    - name: Upload symbols too
      uses: actions/upload-artifact@v4
      with:
        name: symbols
        path: symbols
