name: Compile

on: [push, pull_request]

jobs:
  build-asi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get submodules
        run: git submodule update --init --recursive
      
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Cache build files
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-build-dir
        with:
          path: ChaosMod/build
          key: build

      - name: Compile ASI & Dependencies
        run: |
          cd ChaosMod
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE="Release" -DWITH_DEBUG_PANEL_SUPPORT=1 ../
          ninja
      
      - uses: actions/upload-artifact@v4
        with:
          name: dst-asi
          path: |
            ChaosMod/build/ChaosMod.asi
            ChaosMod/build/ChaosMod.pdb

  build-dotnet:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Get NuGet Packages
        run: msbuild ChaosMod.sln /t:restore /p:RestorePackagesConfig=true /p:Configuration=Release

      - name: Compile Config App
        run: dotnet publish ConfigApp -c Release -o dst

      - name: Compile Voting Proxy
        run: dotnet publish TwitchChatVotingProxy -c Release -o dst
      
      - uses: actions/upload-artifact@v4
        with:
          name: dst-dotnet
          path: dst

  build-misc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Voting Overlay
        run: |
          cd twitchVotingOverlay
          npm install
          npm run compile:prod

      - name: Generate Native Definitions for Lua Runtime
        run: |
          cd scripts
          python generate_natives.py

      - name: Copy to folder
        run: |
          mkdir dst
          cd dst
          cp -r ../twitchVotingOverlay/dist twitchOverlay
          cp ../scripts/natives_def.lua

      - uses: actions/upload-artifact@v4
        with:
          name: dst-misc
          path:
            dst
  
  package:
    needs: [build-asi, build-dotnet, build-misc]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dst-*
          merge-multiple: true
          path: dst

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: dst-*

      - name: Ready up for distribution
        run: |
          cd dst
          mkdir dst
          C:\msys64\usr\bin\wget.exe http://gopong.dev/chaos/data.zip
          7z.exe x data.zip -o"dst\"
          rm data.zip
          cp ChaosMod.asi dst/
          cp ChaosModVConfig.exe dst/chaosmod/
          cp TwitchChatVotingProxy.exe dst/chaosmod/
          cp -r twitchOverlay dst/chaosmod/twitchOverlay/
          cp natives_def.lua dst/chaosmod/
          mkdir symbols
          cp ChaosMod.pdb symbols/
          cp ChaosModVConfig.pdb symbols/
          cp TwitchChatVotingProxy.pdb symbols/
          cd ..

      - name: Copy files to Inno source folder
        run: |
          cp -r dst\dst\ Installer\src\

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Installer/install.iss
          options: /O+

      - name: Upload :)
        uses: actions/upload-artifact@v4
        with:
          name: chaosmod
          path: dst/dst
          include-hidden-files: true
      
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: Installer/dst/ChaosModInstaller.exe
          include-hidden-files: true

      - name: Upload symbols too
        uses: actions/upload-artifact@v4
        with:
          name: symbols
          path: dst/symbols
          include-hidden-files: true